### ISSUE TITLE
Illegal PV move

### ISSUE THREAD

**Issue by JoAnnP38** [GiacomoPorpiglia/Mida#19]
When running Mida in cutechess-cli, it causes cutechess to essentially SPAM warning messages about an illegal move being in the reported PV. Need to make sure that all the moves in the PV are legal moves to prevent this. 

EXAMPLE:
Warning: Illegal PV move e7c5b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 Be7 dxc5 e7c5b
Warning: Illegal PV move d5b4n from MIDA 2.2 (113)
Warning: PV: Be7 Bd3 cxd4 exd4 Nd5 Bg3 d5b4n
Warning: Illegal PV move b5d3b from MIDA 2.2 (113)
Warning: PV: d5 Bb5+ Nbd7 c3 Be7 Qe2 O-O a4 a6 b5d3b
Warning: Illegal PV move f1e1r from MIDA 2.2 (113)
Warning: PV: Be7 Bd3 O-O c3 d6 O-O Nbd7 f1e1r
Warning: Illegal PV move b5d3b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5d3b
Warning: Illegal PV move b5a4b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5a4b
Warning: Illegal PV move b5a4b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5a4b
Warning: Illegal PV move b5c6b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5c6b
Warning: Illegal PV move b5d3b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5d3b
Warning: Illegal PV move b5d3b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5d3b
Warning: Illegal PV move b5d3b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5d3b
Warning: Illegal PV move b5c6b from MIDA 2.2 (113)
Warning: PV: Nc6 c3 d5 Bb5 a6 b5c6b
Warning: Illegal PV move e7c5b from MIDA 2.2 (113)
Warning: PV: a6 Be2 Be7 c3 O-O Bh2 h6 dxc5 e7c5b
Warning: Illegal PV move d6e7q from MIDA 2.2 (113)
Warning: PV: a6 Be2 d5 c3 Bd6 Bxd6 Qxd6 O-O d6e7q
Warning: Illegal PV move d3e2b from MIDA 2.2 (113)
Warning: PV: a6 Bd3 cxd4 exd4 Nb4 d3e2b
Warning: Illegal PV move d6e7q from MIDA 2.2 (113)
Warning: PV: a6 Be2 d5 c3 Bd6 Bxd6 Qxd6 O-O O-O Qc2 d6e7q
Warning: Illegal PV move d6e7q from MIDA 2.2 (113)
Warning: PV: a6 Be2 d5 c3 Bd6 Bxd6 Qxd6 O-O O-O Qc2 d6e7q
Warning: Illegal PV move d6f4b from MIDA 2.2 (113)
Warning: PV: a6 Be2 d5 O-O Bd6 dxc5 d6f4b
Warning: Illegal PV move f1e1r from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 O-O Bd6 Bxd6 Qxd6 c3 O-O f1e1r
Warning: Illegal PV move f1e1r from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 O-O Bd6 Bxd6 Qxd6 c3 O-O f1e1r
Warning: Illegal PV move f1e1r from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 O-O Bd6 Bxd6 Qxd6 c3 O-O f1e1r
Warning: Illegal PV move f8d8r from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 c3 Bd6 Bxd6 Qxd6 O-O O-O a4 f8d8r
Warning: Illegal PV move d6c7q from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 c3 Bd6 Bxd6 Qxd6 Qe2 O-O dxc5 bxc5 e4 d6c7q
Warning: Illegal PV move d6f4b from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 c3 Bd6 O-O d6f4b
Warning: Illegal PV move d6f4b from MIDA 2.2 (113)
Warning: PV: a6 Bd3 d5 c3 Bd6 O-O d6f4b

**Comment by GiacomoPorpiglia** [comment]
Hi JoAnn,
yes, Mida 2.2 had a buggy move printing which as you can see caused it to print the letters next to the moves as if they were promotions, when they actually aren't. 
This doesn't cause serious errors, because cutechess still accepts the moves, but it's not nice for sure.
This was solved in the next version, starting from 2.3
